### ISSUE TITLE
Desktop GUI

### ISSUE THREAD

**Issue by tlentz** [tlentz/d2modmaker#15]
Want to create a desktop gui that is linked to the cfg.json directly so that it is easier to visually see/change settings.

# Wants
* Be able to edit all values in cfg.json through gui
* re-randomize seed button
* run button

**Comment by tbal999** [comment]
Sure, will take a look at this and get back to you.

**Comment by tbal999** [comment]
<script src="https://gist.github.com/tbal999/05fa342e3c600f4e6f6073e621071bff.js"></script>

**Comment by tlentz** [comment]
@tbal999 
> https://gist.github.com/tbal999/05fa342e3c600f4e6f6073e621071bff#file-load_save_cfg-go

Hi, I am already doing something similar to this.  I do like that.

Web app could be fine if we can wrap it into a desktop app (like electron).  This will be reading/writing files so I want to avoid downloading anything.

An option to be able to launch d2 or plugy with -direct -txt and pointing to the generated data folder would be helpful.

@nokka told me to take a look at https://github.com/nokka/slashdiablo-launcher
I just haven't gotten around to it.

**Comment by tlentz** [comment]
Also @tbal999 sorry, I just turned on notifications.  I didn't see any of your comments until now.

**Comment by tbal999** [comment]
No problem haha.

You can do local web-apps with Go, I've built web-apps for local applications like parsers before.
I could put together a simple one then you can add additional functionality to it.

**Comment by tlentz** [comment]
Sure, it is an open source project if you want to open a PR.  I am also brand new to Go.  I wanted to learn the language which is what inspired this project.  @tbal999 I have less than a weekend of go experience.  I am a fan of web based apps though.

**Comment by tbal999** [comment]
Fair enough i'll raise a PR - good luck with your Go journey.

I'm trying to learn Javascript myself!

**Comment by tlentz** [comment]
great, I do most of my frontend web apps using Elm which compiles to js and has js interop.

I just created a discord for this project too for some better communication and screenshots and stuff.  I updated the readme to include the invite link.

**Comment by tbal999** [comment]
I've still got this on my radar just been busy. Just letting you know.

**Comment by tlentz** [comment]
> I've still got this on my radar just been busy. Just letting you know.

awesome, thanks!  do you want to join the dev discord channel?

**Comment by tbal999** [comment]
Sure, i'll join :)

**Comment by tbal999** [comment]
I'm going to take some time out today to add a frontend, will see where it takes me.

**Comment by tlentz** [comment]
> Sure, i'll join :)

cool, ping me and ill add you to the dev channel

**Comment by tlentz** [comment]
> I'm going to take some time out today to add a frontend, will see where it takes me.

👍
