### ISSUE TITLE
Game crashes with Cowzzz option enabled on 1.14b and 1.14d

### ISSUE THREAD

**Issue by beneyal** [tlentz/d2modmaker#66]
Hi,

I don't know if the mod is supposed to work on 1.14, but me and two others tried it on 1.14b and 1.14d and can confirm the mod works, as long as Cowzzz isn't enabled.

If Cowzzz is enabled, the game crashes on character creation. On 1.14b, the error is:
![image](https://user-images.githubusercontent.com/3891274/96325172-7147c100-102e-11eb-9538-0f53d4e6b142.png)

Thank you so much for your work!

**Comment by Warren1001** [comment]
info not found by me, but the other of 'two others':
For that Cowzzz thing: What it does, it changes hcIdx (hardcoded index) of The Cow King to 1, and now there's no proper hcIdx of Cow King anywhere in the file, so in 1.14 game checks it, that's why it crashes.

**Comment by tlentz** [comment]
> info not found by me, but by the other of 'two others':
> For that Cowzzz thing: What it does, it changes hcIdx (hardcoded index) of The Cow King to 1, and now there's no proper hcIdx of Cow King anywhere in the file, so in 1.14 game checks it, that's why it crashes.

Interesting, thanks.  So the software uses the 1.13c source files built in.  This may be causing the problems with 1.14.

**Comment by tlentz** [comment]
Fixed here https://github.com/tlentz/d2modmaker/pull/69
