### ISSUE TITLE
Recognized as virus

### ISSUE THREAD

**Issue by bencze1** [tlentz/d2modmaker#67]
Download is detected as trojan by a few major antivirus engines. I would suggest to clarify it with the respective vendors if this is a false positive.

![image](https://user-images.githubusercontent.com/25345171/96354564-45811580-10d8-11eb-834e-41b31fda9edb.png)

**Comment by lucaspanayiotou** [comment]
also recognized as a trojan by windows defender

![image](https://user-images.githubusercontent.com/31956847/97501233-dbcefa00-1968-11eb-90d1-51a6a00ccad4.png)

**Comment by tlentz** [comment]
This may be because it is not code signed, it is open source though so anyone can see that there are no viruses.

**Comment by Kongolan** [comment]
@tlentz Can you add building instructions, so we know how to rebuild it from the source provided? Thanks in advance.
