### ISSUE TITLE
Failed to extract

### ISSUE THREAD

**Issue by Jackleg-Miner** [tlentz/d2modmaker#68]
Don't know if this is just an issue on my end, but, I cannot extract this file no matter how I try.  It just fails continually.  Tried different extraction apps, different locations, different permissions, with and without antivirus.  I don't know if I'm just missing something simple but usually it isn't this difficult for me to extract a file to a location.

**Comment by tlentz** [comment]
I am planning on finding some time to turn this into a desktop app via electron and making the install / run / update process much more simple.  The current release is still a pre release (pre 1.0).  Hopefully I can do this in the next week or so, but I am limited for time.

In the meantime, there is a support channel in the discord where people are very helpful.
