### ISSUE TITLE
Improving Monster Density

### ISSUE THREAD

**Issue by Necrolis** [tlentz/d2modmaker#81]
Since a lot of people seem to enjoy the density, though it might be nice to give some advice on improving it/allowing greater density:

1) MonDen in levels is cap at 10000 (10% chance to spawn a pack per 3x3 subtiles), this means you can't actually really cap out density. However if you increase the MinGrp/MaxGrp fields in monstats you can bypass this without a code edit (though you need to just avoid this for PrimeEvils, NPCs or special bosses -- all of these can be skipped by checking the relevant flags in monstats).

2) MonUMin/MonUMax caps at 255, so you might want to check for this to avoid rollovers.

**Comment by Amek206** [comment]
Yeah we noticed the 10000 cap which is why we maxed the multiplier at 30 I believe so we could achieve 10000 minimum on all/most zones.

Thanks for that tip, will look into this. Really great since we are trying to avoid any types of code edit at this stage of the program.

**Comment by Amek206** [comment]
We are getting closer to a better density option thanks to your tips. We also found a bug to fix haha. 

Cheers

https://www.youtube.com/watch?v=OV2-MMREu_w

**Comment by tlentz** [comment]
Done here. 32946da0c2a6022346dc6987a13dc6a557d7c8fd
